apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: logistics-erp
data:
  ENV: "production"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "redis-service.logistics-erp.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.logistics-erp.svc.cluster.local:9092"
  ELASTICSEARCH_HOST: "elasticsearch-service.logistics-erp.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200"
  MINIO_HOST: "minio-service.logistics-erp.svc.cluster.local"
  MINIO_PORT: "9000"
  JAEGER_ENDPOINT: "http://jaeger-service.logistics-erp.svc.cluster.local:14268/api/traces"