apiVersion: 1

datasources:
  - name: Elasticsearch-Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logistics-logs-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: "message"
      logLevelField: "level"
      maxConcurrentShardRequests: 5
      timeout: "30s"
      interval: "Daily"
      includeFrozen: false
      authType: none
    editable: true
    isDefault: false